### ISSUE TITLE
[KonvaTimeLine] Invalid start/end value error

### ISSUE THREAD

**Issue by CrisGrud** [melfore/konva-timeline#132]
If passing invalide range value to KonvaTimeLine,  it draws Konva with date.now as start range value and the end of next unit of measure of selected Resolution(min-hrs, day-week) as end range value.
Konva with invalid range value is void (with no tasks).

**Comment by luciob** [comment]
The function to change is `getValidTime`.
Add support for `Date` of JS. Consider that this method is used for validation of range and tasks.
Run the tests (file `time.test.ts`) and check that they all pass.
Check also execution time to remain below 250ms (test fails after 500ms).
